config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'pages#home'

	get '/home' => 'pages#home'

	# Serve websocket cable requests in-process
	mount ActionCable.server => '/cable'

	get '/admin' => 'pages#admin_settings'	
	get '/about' => 'pages#about'
	get '/register' => 'users#new'
	get '/login' => 'logins#new'
	
	resources :users, except: [:new] do
		member do
			get :confirm_email
		end
	end

	resources :markets do
		member do
			get '/join' => 'markets#join'
			get '/leave' => 'markets#leave'
			get '/complete' => 'markets#results_form'
			post '/complete' => 'markets#complete'
			get '/results' => 'markets#results'
			resources :messages
			resources :market_outcomes do
				post '/new_back' => 'backs#create'
				post '/new_lay' => 'lays#create'
				post '/new_hit' => 'hits#create'
			end
		end
	end

	get '/login' => 'logins#new'
	post '/login' => 'logins#create'
	get '/logout' => 'logins#destroy'

end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_markets, dependent: :destroy
	has_many :markets, through: :user_markets
	has_many :messages
	has_many :backs
	has_many :lays
	#TODO Are the below two references doing anything?
	has_many :wins, class_name: 'Result', foreign_key: 'layer_id'
	has_many :loses, class_name: 'Result', foreign_key: 'backer_id'

	has_many :payments, class_name: 'Payment', foreign_key: 'payer_id'
	has_many :receipts, class_name: 'Payment', foreign_key: 'receiver_id'

	before_create :confirmation_token
 	before_save { self.email = email.downcase }

	validates :firstname, presence: true
	validates :secondname, presence: true
	validates :username, presence: true, uniqueness: true, length: { minimum: 6, maximum: 72}, on: :create
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 },
										uniqueness: {case_sensitive: false},
										format: {with: VALID_EMAIL_REGEX}
	validates :password, presence: true, length: { minimum: 8, maximum: 72}, on: :create

	has_secure_password

	def email_activate
		self.email_confirmed = true
		self.confirm_token = nil
		save!
	end


private

	def confirmation_token
		if self.confirm_token.blank?
		  self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_user, except: [:new,  :create, :confirm_email]
	before_action :require_user_is_self, only: [:show, :update]
	before_action :require_admin_user, except: [:new,  :create, :show, :confirm_email, :update]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
	    @user = User.new(user_params)

		if @user.save
			UserMailer.registration_confirmation(@user).deliver_now
			flash[:success] = "Please confirm your email address before continuing"
			redirect_to root_path	
		else
      		render :new
    	end

  	end

  	def show
  		@user = User.find(params[:id])
  		
  	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	    if @user.update(user_params)
	      flash[:success] = "You have sucessfully updated your information"  
	      redirect_to user_path(@user)
	    else
	      render :edit
	    end
	end

	def confirm_email
		user = User.find_by_confirm_token(params[:id])
		if user
			user.email_activate
			flash[:success] = "Welcome to Make Your Market! Your email has been confirmed.
			Please sign in to continue."
			redirect_to login_path
		else
			flash[:error] = "Sorry. User does not exist"
			redirect_to root_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:firstname, :secondname, :username, :email, :password)
	end

	def require_user_is_self
		#user can only see/update their own details
		redirect_to root_path if current_user != User.find(params[:id]) && !admin_user?
	end

	def require_admin_user
		redirect_to root_path if !admin_user?
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class= "col-md-6 col-md-offset-3">

  <div class= "form">

    <h2 class="form-signin-heading">Edit your details</h2> 

      <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :firstname %>
      <%= f.text_field :firstname, class:"form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :secondname %>
        <%= f.text_field :secondname, class:"form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-control" %>
    </div>
    <div class="form-group">
        <% if @user.new_record? %>
          <%= f.label :password %>
          <%= f.password_field :password, class:"form-control" %>
        <% end %>
    </div>
    
      <div class="row">
        <div class= "col-xs-6">
          <%= f.submit(@user.new_record? ? 'New User' : 'Edit User', class: "btn btn-primary btn-block") %>
        </div>
        <div class= "col-xs-6">
          <%= link_to "Your markets", markets_path(joined: true), class: "btn btn-primary btn-block" %>
        </div>
      </div>
      
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<p class="text-center"><%= link_to "New User", "/register", class: "btn btn-primary" %></p>

<div class="row">
	<div class="col-md-6 col-md-offset-3">	
		<h2>Users</h2>

		<% @users.each do |user| %>
			<div class="panel">
				<%= link_to "#{user.username}", user_path(user), class: "h4" %>
			</div>
		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">      
          <%= form_for @user, class: "form-signin" do |f| %>
            <h2 class="form-signin-heading">Register</h2>

          <div class="form-group">            
            <%= f.label :firstname, class: "sr-only" %>
	          <%= f.text_field :firstname, class: "form-control", placeholder: 'First Name', :required => true, :autofocus => true %>
          </div>

          <div class="form-group">             
            <%= f.label :secondname, class: "sr-only" %>
	          <%= f.text_field :secondname, class: "form-control", placeholder: 'Last Name', :required => true %>
          </div>

          <div class="form-group"> 
            <%= f.label :username, class: "sr-only" %>
            <%= f.text_field :username, class: "form-control", placeholder: 'Username', :required => true %>
          </div>

          <div class="form-group"> 
            <%= f.label :email, class: "sr-only" %>
	          <%= f.text_field :email, class: "form-control", placeholder: 'Email', :required => true %>
          </div>

          <div class="form-group">       	    
      	    <%= f.label :password, class: "sr-only" %>
      	    <%= f.password_field :password, class: "form-control", placeholder: 'Password' , :required => true %>
          </div>

          <div class="form-group">             
            <%= f.submit 'Register', class: 'btn btn-lg btn-primary btn-block'%>
          </div>

          </form>
          </br>
          <%= link_to "Already a member?", login_path %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1><%= "#{@user.firstname} #{@user.secondname}" %> <small><%= "#{@user.username}" %></small> </h2>
        </div>
    </div>

    <div class="row">
        <%= render 'form' %>
    </div>

    <br>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= link_to "Admin", admin_path %>
        </div>
    </div>
    

</div>