config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'pages#home'

	get '/home' => 'pages#home'

	# Serve websocket cable requests in-process
	mount ActionCable.server => '/cable'

	get '/admin' => 'pages#admin_settings'	
	get '/about' => 'pages#about'
	get '/register' => 'users#new'
	get '/login' => 'logins#new'
	
	resources :users, except: [:new] do
		member do
			get :confirm_email
		end
	end

	resources :markets do
		member do
			get '/join' => 'markets#join'
			get '/leave' => 'markets#leave'
			get '/complete' => 'markets#results_form'
			post '/complete' => 'markets#complete'
			get '/results' => 'markets#results'
			resources :messages
			resources :market_outcomes do
				post '/new_back' => 'backs#create'
				post '/new_lay' => 'lays#create'
				post '/new_hit' => 'hits#create'
			end
		end
	end

	get '/login' => 'logins#new'
	post '/login' => 'logins#create'
	get '/logout' => 'logins#destroy'

end

app/views/pages/about.html.erb
<nav class="hover-underline-menu" data-menu-underline-from-center>
  <ul class="menu align-center">
    <li>
      <%= link_to login_path do %>
        <i class="fa fa-sign-in"> Sign-in</i>
      <% end %>
    </li>
  </ul>
</nav>

<header class="subnav-hero-section">
  <h1 class="subnav-hero-headline"><span class="main-name">MYM</span></h1>
  <ul class="subnav-hero-subnav">
    <li><a href="#">Browse markets</a></li>
    <li><a href="#" class="is-active">Sign up</a></li>
    <li><a target="_blank" href="https://zurb.com/responsive">About mym</a></li>
  </ul>
</header>

app/views/pages/admin_settings.html.erb
<%= link_to "Show Users", users_path %>

app/views/pages/home.html.erb
<header id="page-top">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-text">
					<span class="typewrite" data-period="2000" data-type='[ "Make your mark", "Settle your scores", "MAKE YOUR MARKET" ]'>
					    <span class="wrap"></span>
					</span>
                </div>
            </div>
        </div>
        <div class="row">
        	<div class="col-lg-12">
				<i class="fa fa-play" aria-hidden="true" data-selected="true"></i>
				<i class="fa fa-stop" aria-hidden="true" data-selected="false"></i>
        	</div>
        </div>
    </div>
</header>

<div class="content-wrapper">
    <section class="first-color" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-primary">
                    <p>Make your market allows you to create your own betting markets and exchanges. Whatever you can think of can become a market</p>
                	<p>It's time to settle those scores...</p>
                </div>
            </div>
        </div>
    </section>
    <section class="second-color" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>How it works</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
                </div>
                <div class="col-lg-4">
                    <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
                </div>
            </div>
        </div>
    </section>
</div>