config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'pages#home'

	get '/home' => 'pages#home'

	# Serve websocket cable requests in-process
	mount ActionCable.server => '/cable'

	get '/admin' => 'pages#admin_settings'	
	get '/about' => 'pages#about'
	get '/register' => 'users#new'
	get '/login' => 'logins#new'
	
	resources :users, except: [:new] do
		member do
			get :confirm_email
		end
	end

	resources :markets do
		member do
			get '/join' => 'markets#join'
			get '/leave' => 'markets#leave'
			get '/complete' => 'markets#results_form'
			post '/complete' => 'markets#complete'
			get '/results' => 'markets#results'
			resources :messages
			resources :market_outcomes do
				post '/new_back' => 'backs#create'
				post '/new_lay' => 'lays#create'
				post '/new_hit' => 'hits#create'
			end
		end
	end

	get '/login' => 'logins#new'
	post '/login' => 'logins#create'
	get '/logout' => 'logins#destroy'

end

app/models/market.rb
 class Market < ApplicationRecord
	has_many :user_markets, dependent: :destroy
	has_many :users,  through: :user_markets
	has_many :messages
	belongs_to :market_type
	belongs_to :market_status
	has_many :market_outcomes, dependent: :destroy, inverse_of: :market
	has_many :backs, through: :market_outcomes
	has_many :lays, through: :market_outcomes
	has_many :results, through: :market_outcomes
	has_many :payments

	scope :not_marked_as_complete, -> { where('market_status_id != 3') }
	scope :marked_as_complete, -> { where('market_status_id = 3') }
	
	validates :market_status_id, presence: true
	validates :name, presence: true
	validates :description, presence: true

	before_destroy :has_backs_or_lays, prepend: true
	
	accepts_nested_attributes_for :market_outcomes, allow_destroy: true

	def self.founded_by_user(current_user)
		current_user.markets.includes(:user_markets).where('user_markets.is_founder = ?', true)
	end

	def self.joined_by_user(current_user)
		current_user.markets
	end
	
	#instance methods
	def mkfounder
		users.includes(:user_markets).where('user_markets.is_founder = ?', true).first
	end

	private

		def has_backs_or_lays
			if self.lays.any? || self.backs.any?
				errors.add(:base, "Bets have been made against this market - it can not be deleted")
				throw :abort
			end
		end

end
 

app/models/market_type.rb
class MarketType < ApplicationRecord
	has_many :markets
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

	before_action :require_user, except: [:show, :index]
	before_action :require_founder, only: [:edit, :update, :destroy, :complete]
	before_action :redirect_if_completed_market, only: [:show, :edit, :update, :join, :leave]
	before_action :redirect_if_not_completed_market, only: [:results]
	before_action :redirect_if_results_already_entered, only: [:results_form]

	
	def index
		@markets = Market.all.not_marked_as_complete
		@markets = Market.joined_by_user(current_user).not_marked_as_complete if params[:joined].present? && current_user
		@markets = Market.joined_by_user(current_user).marked_as_complete if params[:joinedandcomplete].present? && current_user
	end

	def show
		market = Market.find(params[:id])
		@market = MarketPresenter.new(market, view_context)
		@message = Message.new
	end

	def new
		@market = Market.new
		#create blank outcome
		1.times { @market.market_outcomes.build }
	end

	def create
		@market = Market.new(market_params)
		@market.user_markets << UserMarket.new(user: current_user, is_founder: true)
	    if @market.save(market_params)
			flash[:success] = "You have sucessfully created this market"
			redirect_to market_path(@market)
	    else
	      render :new
	    end
	end

	def edit
		@market = Market.find(params[:id])
		if @market.market_outcomes.empty?
			1.times { @market.market_outcomes.build }
		end
	end
	
	def update
		@market = Market.find(params[:id])
	    if @market.update(market_params)
	      flash[:success] = "You have sucessfully updated this market"  
	      redirect_to market_path(@market)
	    else
	      render :edit
	    end
	end
	
	def destroy
		@market = Market.find(params[:id])
	    if @market.destroy
		    flash[:success] = "Market Deleted"
		    redirect_to markets_path	    	
	    else
	    	render :edit	    	
	    end
	end

	def results_form
		market = Market.find(params[:id])
		@market = MarketPresenter.new(market, view_context)
	end

	def complete
		@market = Market.find(params[:id])
		@market.assign_attributes(market_params)
		market_result_processor = ProcessMarketResults.new(@market)
		market_payments_processor = ProcessMarketPayments.new(@market)
		
		begin
			ActiveRecord::Base.transaction do
				@market.assign_attributes(market_status_id: 3)
				@market.save!
				market_result_processor.process.each do |result|
					if !result.valid?
						@market.errors.add(:base, "#{result.market_outcome.outcome} cannot be blank - it has hits against it.")
					end
					result.save!
				end
				market_payments_processor.process
			end
			
			ActionCable.server.broadcast "all_users_in_market_#{params[:id]}", "reload_page": true
	
			redirect_to market_path(@market)
			
		rescue
			render :results_form
		end

	end
	
	def results
		#redirect here if (and only if) market is completed
		market = Market.find(params[:id])
		@market = MarketPresenter.new(market, view_context)

	end

	def join

		market = Market.find(params[:id])
		@user_market = market.user_markets.build(user: current_user)
		@market = MarketPresenter.new(market, view_context)

		respond_to do |format|
			if @user_market.save
				format.html { redirect_to market_path(@market) }
				format.js { }
			else	
				format.html { redirect_to market_path(@market) }	
			end
		end	
	end

	def leave
		market = Market.find(params[:id])
		@user_market = market.user_markets.where(user: current_user).first
		@market = MarketPresenter.new(market, view_context)

		respond_to do |format|
			if @user_market.destroy
				format.html { redirect_to market_path(@market) }
				format.js { }
			else	
				format.html { redirect_to market_path(@market) }
				format.js {}
			end
		end
	end


	private
	
	def market_params
		params.require(:market).permit(:name, :description, :market_type_id, :market_status_id, market_outcomes_attributes: [:id, :outcome, :_destroy, :result])	
	end

	def render_user(user)
		render(partial: 'user', locals: { user: user })
	end

	def market_founder?(market)
		!!(market.mkfounder == current_user)
	end

	def require_founder
		if not market_founder?(Market.find(params[:id]))
		  flash[:danger] = "You need to be the market founder see this page"
		  redirect_to root_path
		end
	end
	
	def redirect_if_completed_market
		redirect_to results_market_path(Market.find(params[:id])) if Market.find(params[:id]).market_status_id == 3
	end

	def redirect_if_not_completed_market
		#can only see results of a completed market
		redirect_to market_path(Market.find(params[:id])) if Market.find(params[:id]).market_status_id != 3
	end

	def redirect_if_results_already_entered
		#can only see results of a completed market
		redirect_to market_path(Market.find(params[:id])) if Market.find(params[:id]).results.any?
	end
end

app/helpers/market_helper.rb
module MarketHelper
end

app/views/markets/_form.html.erb
<div id="error_partial">
    <%= render "shared/errors", obj: @market %>
</div>

<div class= "container">
  <div class="row">

    <div id= "new_market_form" class= "col-md-8 col-md-offset-2">

        <%= form_for @market, html: { id: "market_form" } do |f| %>

          <h2 class="form-signin-heading">
            <%= @market.new_record? ? 'Create your market' : 'Edit your market' %>
          </h2>

          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label :name %>
              <%= f.text_field :name, class:"form-control" %>
            </div>
            <div class="form-group col-md-6">
              <%= f.label :description %>
              <%= f.text_area :description, class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label 'Market Type' %>
              <%= f.collection_select(:market_type_id, MarketType.all, :id, :mechanism, {}, {class: "form-control"}) %>
            </div>
            <div class="form-group col-md-6">
              <%= f.label 'Outcomes' %>
              <Ul class="list-unstyled" id="new_outcomes_input_group">
                <%= f.fields_for :market_outcomes do |mo_form| %>
                    <li>
                        <%= mo_form.text_field :outcome, html_options={placeholder:'New Outcome', class: "form-control"} %>
                    </li>                 
                <% end %>               
              </ul>
              <button type="button" class="btn btn-sm btn-primary btn-block"  id="add_outcome">Add outcome</button>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6 form-check form-check-inline">
                <%= f.check_box :market_status_id, {id: "publish_checkbox", class:"form-check-input"}, "2", "1" %>
                <%= f.label 'Publish market?', class:"form-check-label" %>
            </div>

            <div class="form-group col-xs-12">
              <%= f.submit(@market.new_record? ? 'Save New Market' : 'Save Changes', class: "btn btn-success btn-block") %>
            </div>
          </div>

        <% end %>

    </div>

  </div>
</div>

app/views/markets/_form_once_published.html.erb
<div id="error_partial">
    <%= render "shared/errors", obj: @market %>
</div>

<div class= "container">
  <div class="row">
    <div id= "new_market_form" class= "col-md-8 col-md-offset-2">
      <h4>There are bets made against this market - the only change allowed is the creation of additional outcomes</h4>

      <%= form_for @market, html: { id: "market_form" } do |f| %>

        <h2 class="form-signin-heading">
          <%= @market.new_record? ? 'Create your market' : 'Edit your market' %>
        </h2>

        <div class="form-row">
          <div class="form-group col-md-8">
            <%= f.label 'Outcomes' %>
            <Ul class="list-unstyled" id="new_outcomes_input_group">
              <%= f.fields_for :market_outcomes do |mo_form| %>
                  <li>
                      <%= mo_form.text_field :outcome, html_options={placeholder:'New Outcome', class: "form-control", disabled: "disabled"} %>
                  </li>                 
              <% end %>               
            </ul>
            <button type="button" class="btn btn-sm btn-primary btn-block"  id="add_outcome">Add outcome</button>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-8"">
            <%= f.submit(@market.new_record? ? 'Save New Market' : 'Save Changes', class: "btn btn-success btn-block") %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/markets/_outcome.html.erb
  <% mo_presenter = MarketOutcomePresenter.new(outcome, self) %>

  <div class="row">
    <h5 class="text-center"><%= mo_presenter.outcome %></h5>
  </div>

  <div class="row">
    <div class= "col-xs-6 bet-group">

      

      <p class="text-center">Back</p>

      <div class="button-container">
      <!-- Trigger the new back modal with a button -->
      <button type="button" class="btn btn-sm btn-info btn-lg bet-button pull-right" data-toggle="modal" data-target=<%= "#back_modal_#{outcome.id}" %>>Create<br>Back Odds</button>

      <!-- Modal -->
      <div id=<%= "back_modal_#{outcome.id}"%> class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content--> 
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">New Back</h4>
            </div>
            <%= form_tag(market_outcome_new_back_path([mo_presenter.market], [mo_presenter]), remote: true) do %>
            <div class="modal-body">
              <% if mo_presenter.market.market_type.id == 1 %>
              <p>Set your odds: <%= number_field_tag :odds, mo_presenter.set_minimum_back_odds, min: mo_presenter.set_minimum_back_odds, max: 10000, step: 0.1, class: "short-width-input"%></p>
              <% else %>
              <p>Set your back level: <%= number_field_tag :odds, mo_presenter.set_minimum_back_odds, min: mo_presenter.set_minimum_back_odds, max: 10000, step: 0.1, class: "short-width-input"%></p>
              <%end%>
              <p>How much?: £<%= number_field_tag :original_amount, 5, min: 0, max: 10000, step: 0.1, class: "short-width-input"%></p>
            </div>
            <div class="modal-footer">
              <%= submit_tag "Submit", class: "btn btn-default" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
            <% end %>
          </div>

        </div>
      </div>

      <!-- bet collection = all lays of current market outcome -->
      <% bet_collection = mo_presenter.lays.non_zero_current_amount %>
      <% mo_presenter.create_bet_hash(bet_collection, :lays).each do |odds, amount| %>

      <% str_odds = odds.to_s.tr('.','_') %>

      <button type="button" class="btn btn-sm btn-danger pull-right bet-button" data-toggle="modal" data-target=<%= "#hit_back_modal_#{outcome.id}_#{str_odds}" %>><%= odds %> <br> <%= "(£#{amount})" %></button>

      <!-- Modal -->
      <div id=<%= "hit_back_modal_#{outcome.id}_#{str_odds}" %> class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content--> 
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Hit?</h4>
            </div>
            <%= form_tag(market_outcome_new_hit_path([mo_presenter.market], [mo_presenter]), remote: true) do %>
            <div class="modal-body">
              <p><%= "Back #{outcome.outcome} @ #{odds}?" %></p>
              <p>Amount: £<%= number_field_tag :original_amount, amount, min: 0.1, max: amount, step: 0.1, class: "short-width-input"%></p>
            </div>
            <div class="modal-footer">
              <%= hidden_field_tag :odds, odds %>
              <%= hidden_field_tag :bet_direction, :back %>
              <%= submit_tag "Submit", class: "btn btn-default" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
            <% end %>
          </div>

        </div>
      </div>

      <% end %>

      </div>

    </div>

    <div class= "col-xs-6 bet-group">
      <p class="text-center">Lay</p>

      <div class="button-container pull">

      <!-- Trigger the new lay modal with a button -->
      <button type="button" class="btn btn-sm btn-info btn-lg pull-left bet-button" data-toggle="modal" data-target=<%= "#lay_modal_#{outcome.id}" %>>Create<br>Lay Odds</button>

      <!-- Modal -->
      <div id=<%= "lay_modal_#{outcome.id}"%> class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content--> 
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">New Lay</h4>
            </div>
            <%= form_tag(market_outcome_new_lay_path([mo_presenter.market], [mo_presenter]), remote: true) do %>
            <div class="modal-body">
              <% if mo_presenter.market.market_type.id == 1 %>
              <p>Set your odds: <%= number_field_tag :odds, mo_presenter.set_maximum_lay_odds, min: 0, max: mo_presenter.set_maximum_lay_odds, step: 0.1, class: "short-width-input"%></p>
              <p>How much?: £<%= number_field_tag :original_amount, 0, min: 0, max: 10000, step: 0.1, class: "short-width-input"%></p>
              <% else %>
              <p>Set your lay level: <%= number_field_tag :odds, mo_presenter.set_maximum_lay_odds, min: 0, max: mo_presenter.set_maximum_lay_odds, step: 0.1, class: "short-width-input"%></p>
              <p>How much?: £<%= number_field_tag :original_amount, 0, min: 0, max: 10000, step: 0.1, class: "short-width-input"%></p>              
              <% end %>
            </div>
            <div class="modal-footer">
              <%= submit_tag "Submit", class: "btn btn-default" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
            <% end %>
          </div>

        </div>
      </div>

      <% bet_collection = mo_presenter.backs.non_zero_current_amount %>
      <% mo_presenter.create_bet_hash(bet_collection, :backs).each do |odds, amount| %> 

      <% str_odds = odds.to_s.tr('.','_') %>
      <!-- Trigger the new lay modal with a button -->
      <button type="button" class="btn btn-sm btn-primary pull-left bet-button" data-toggle="modal" data-target=<%= "#hit_lay_modal_#{outcome.id}_#{str_odds}" %>><%= odds %> <br> <%= "(£#{amount})" %></button>

      <!-- Modal -->
      <div id=<%= "hit_lay_modal_#{outcome.id}_#{str_odds}" %> class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content--> 
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Hit?</h4>
            </div>
            <%= form_tag(market_outcome_new_hit_path([mo_presenter.market], [mo_presenter]), remote: true) do %>
            <div class="modal-body">
              <p><%= "Lay #{outcome.outcome} @ #{odds}?" %></p>
              <p>Amount: £<%= number_field_tag :original_amount, amount, min: 0.1, max: amount, step: 0.1, class: "short-width-input"%></p>
            </div>
            <div class="modal-footer">
              <%= hidden_field_tag :odds, odds %>
              <%= hidden_field_tag :bet_direction, :lay %>
              <%= submit_tag "Submit", class: "btn btn-default" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
            <% end %>
          </div>

        </div>
      </div>
      
      <% end %>   

      </div>

    </div>
  </div>

app/views/markets/_outcome_stager.html.erb
<!-- This staging partial is included to allow a unique ID div on each market outcome - this allows individual market outcome partials to be refreshed/replaced by ActionCable Broadcasts -->
<div id="mo_<%= outcome_stager.id %>">
	<%= render partial: 'markets/outcome', locals: {outcome: outcome_stager} %>
</div>

app/views/markets/_user.html.erb
<li id="<%=user.email.gsub!('@', '_').gsub!('.', '_')%>"><h4><%= user.username %></h4></li>

app/views/markets/_user_bet.html.erb
<%= "#{user_bet.market_outcome.outcome} - £#{user_bet.current_amount} @ #{user_bet.odds}" %>
<br>

app/views/markets/_user_hit.html.erb
<%= "#{user_hit.back.market_outcome.outcome} - £#{user_hit.amount} @ #{user_hit.back.odds}" %>
<br>

app/views/markets/edit.html.erb
<div class= "container">
  <div class="row">
    <div class= "col-md-8 col-md-offset-2">
        <h2><%= @market.name %><small> Market <%= @market.market_status.market_status %></small></h2>
            <% if @market.market_status_id != 1 %><%= link_to "Enter Market Results", complete_market_path(@market), class:"btn btn-info btn-sm" %><% end %>
            <%= link_to "Delete Market", @market, method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

<% if @market.market_status_id == 1 %>
    <%= render 'form' %>
<% else %>
    <%= render 'form_once_published' %>
<% end %>

app/views/markets/index.html.erb
<div class= "container">
	<div class="row">
		<div class= "col-md-10 col-md-offset-1">
			<ul class="nav nav-tabs">
				<li class="active", id="all_markets">
				<%= link_to "All Live Markets", markets_path %>
				</li>
				<% if logged_in? %>
					<li id="joined_markets">
					<%= link_to "Your Live Markets", markets_path(joined: true) %>
					</li>
					<li id="joined_and_complete_markets">
					<%= link_to "Your Completed Markets", markets_path(joinedandcomplete: true) %>
					</li>					
				<% end %>
			</ul></br>
		</div>
	</div>

	<div class="row">
		<div class= "col-md-8 col-md-offset-2">

		<p class="text-center"><%= link_to "New Market", new_market_path, class: "btn btn-primary" %></p>

		<% @markets.each do |market| %>
		<div class="panel panel-success">
			<div class="panel-heading text-center">
				<p><%= link_to market.name, market_path(market) %></p>
			</div>	
			<div class="panel-body text-center">
				<p><%= market.description %></p>	
			</div>
			<div class="panel-footer text-center">
				<p><span class="pull-right">Outcomes: <%= market.market_outcomes.count %></span>
				<span class="pull-left">Founder: <%= market.mkfounder.firstname %></span></p>
			</div>
		</div>
		<% end %>

		</div>
	</div>
</div>

app/views/markets/new.html.erb
<%= render 'form' %>

app/views/markets/old_join.js.erb
$('#joinleave-market').text('Leave Market');
$('#joinleave-market').attr('class', 'btn btn-warning');
$('#joinleave-market').attr('href', '<%= leave_market_path %>');
$("#user_partial").html("<%= escape_javascript(render partial: 'user', collection: @market.users) %>"); 

app/views/markets/results_form.html.erb
<%= render 'shared/errors', obj: @market %>

<div class= "container">
  <div class="row">

  <!-- TODO need to add logic for spread markets -->

    <div id= "new_market_form" class= "col-md-8 col-md-offset-4">

      <h3>Outcomes</h3>

      <%= form_for @market, url: complete_market_path, method: :post do |f| %>

        <% if @market.market_type.id == 1 %>
          <h4>Tick the checkbox of all outcomes where the backers won</h4>
        <% else %>
          <h4>Enter the result of each outcome</h4>
        <% end %>

        <div class="row">
          <div class= "col-xs-6 col-sm-4">
            <ul class="list-unstyled" id='new_outcomes_input_group'>
              <%= f.fields_for :market_outcomes do |mo_form| %>

                <% if @market.market_type.id == 1 %>
      
                  <li>
                    <%= mo_form.label :outcome, mo_form.object.outcome %>
                      <%= mo_form.check_box :result, class:"form-control" %>
                  </li>        			  
                  <br>

                <% else %>
                
                  <li>
                    <%= mo_form.label :outcome, mo_form.object.outcome %> | Result:
                      <%= mo_form.number_field :result, class: "form-control"%>
                  </li>   
                  <br>
                  <%= mo_form.object.hits.any? %>
                  
                <% end %>
              <% end %>
            </ul>
          </div>      
        </div>

        <%= f.submit "Save results and mark as complete", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/markets/show.html.erb
<div id="error_partial">
    <%= render "shared/errors", obj: @market %>
</div>

<div id="market_show_id" data-category="<%= @market.id  %>" style="display: none;"></div>

<% if current_user %>
<div id="user_show_id" data-category="<%= current_user.id  %>" style="display: none;"></div>
<% end %>

<div class= "container">

    <div class="row">
        <div class= "col-sm-8">
            <div class= "well">
                <h1 class="text-center"><%= @market.name %></h1>
            </div>
        </div>
        <div class= "col-sm-4">
            <div class= "well">
                <p class="market-description"><%= @market.description %></p>
                <h5>Market Type: <b><%= @market.market_type.mechanism %></b></h5>
                <h5>Founder: <b><%= @market.founder_name %></b></h5>
                <h5>Status: <b><%= @market.market_status.market_status %></b></h5>
            </div>
        </div>
    </div>

    <div class="row">

        <div class= "col-sm-8">
            <div class= "well outcome-well">
                <h2 class="text-center">Outcomes</h2>
                <div id="outcome_partial">
                    <%= render partial: "outcome_stager", collection: @market.market_outcomes %>
                </div>
            </div>
        </div>


        <div class= "col-sm-4 right-bar">
            <% if current_user %>
                <div class="row">

                    <div class="panel-group">
                      <div class="panel panel-default">
                        <div class="panel-heading" data-toggle="collapse" href="#collapse1">
                          <h4 class="panel-title">
                            <span>Your Open Bets</span>
                          </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                          <div class="panel-body">
                            <div class= "col-xs-6">
                                <h4>Open Backs</h4>
                                <div id="userbacks_partial">              
                                    <%= render partial: "user_bet", collection: @market.user_backs(current_user, true) %>
                                </div>                
                            </div>
                            <div class= "col-xs-6">
                                <h4>Open Lays</h4>
                                <div id="userlays_partial"> 
                                    <%= render partial: "user_bet", collection: @market.user_lays(current_user, true) %>
                                </div>
                            </div>                                     
                          </div>
                        </div>
                      </div>
                    </div>

                </div>

                <div class="row">

                    <div class="panel-group">
                      <div class="panel panel-default">
                        <div class="panel-heading" data-toggle="collapse" href="#collapse2">
                          <h4 class="panel-title">
                            <span>Your Matched Bets</span>
                          </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                          <div class="panel-body">
                                <% if @market.user_lays(current_user) %>
                                <div class= "col-xs-6" >
                                    <h4>Backs</h4>
                                    <div id="userback_hits_partial">
                                        <% @market.user_backs(current_user).each do |back| %>
                                        <%= render partial: "user_hit", collection: back.hits %>
                                        <% end %>
                                    </div>
                                </div>
                                <div class= "col-xs-6">
                                    <h4>Lays</h4>
                                    <div id="userlay_hits_partial"> 
                                        <% @market.user_lays(current_user).each do |lay| %>
                                        <%= render partial: "user_hit", collection: lay.hits %>
                                        <% end %>
                                    </div>
                                </div>               
                                <% end %>                                   
                          </div>
                        </div>
                      </div>
                    </div>

                </div>
            <% end %>

            <div class="row">
                <div class="panel-group">
                  <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" href="#collapse3">
                      <h4 class="panel-title">
                        <span>Members</span>
                      </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                      <div class="panel-body">
                        <ul id="market-users-list" class="list-unstyled">
                            <div id="user_partial">
                                <%= render partial: "user", collection: @market.users %>
                            </div>
                        </ul>                                  
                      </div>
                    </div>
                  </div>
                </div>
            </div>

            <div class="row">
                <div class="well">
                    <h3 class="text-center">Chat</h3>
                    <div id="messages_partial">
                        <% if @market.messages.any? %>
                        <%= render partial: 'messages/message', collection: @market.messages %>
                        <%end%>
                    </div> 
                    <%= render partial: 'messages/message_form', locals: {message: @message, market: @market}%>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class= "col-md-8">
            <% if current_user && current_user == @market.mkfounder %>
            <p class="text-center"><%= link_to "Edit Market", edit_market_path, class: "btn btn-warning" %></p>
            <% end %>
            <% if @market.user_markets.where(user: current_user).exists? %>
            <p class="text-center inline"><%= link_to "Leave Market", leave_market_path, remote: true, id: "joinleave-market", class: "btn btn-warning" %></p>
            <% else %>
            <p class="text-center inline"><%= link_to "Join Market", join_market_path, remote: true, id: "joinleave-market", class: "btn btn-primary" %></p>
            <% end %> 
        </div>
    </div>
</div>