config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'pages#home'

	get '/home' => 'pages#home'

	# Serve websocket cable requests in-process
	mount ActionCable.server => '/cable'

	get '/admin' => 'pages#admin_settings'	
	get '/about' => 'pages#about'
	get '/register' => 'users#new'
	get '/login' => 'logins#new'
	
	resources :users, except: [:new] do
		member do
			get :confirm_email
		end
	end

	resources :markets do
		member do
			get '/join' => 'markets#join'
			get '/leave' => 'markets#leave'
			get '/complete' => 'markets#results_form'
			post '/complete' => 'markets#complete'
			get '/results' => 'markets#results'
			resources :messages
			resources :market_outcomes do
				post '/new_back' => 'backs#create'
				post '/new_lay' => 'lays#create'
				post '/new_hit' => 'hits#create'
			end
		end
	end

	get '/login' => 'logins#new'
	post '/login' => 'logins#create'
	get '/logout' => 'logins#destroy'

end

app/views/layouts/_messages.html.erb
<div class="container">  
  <div class="row">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="header-main">
    <nav class="navbar navbar-default">
        <div class="container">
            <%= link_to "MYM", root_path, class: "navbar-brand" %>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">markets <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "all live markets", markets_path %></li>
                          <li><%= link_to "your live markets", markets_path(joined: true) %></li>
                          <li><%= link_to "your completed markets", markets_path(joinedandcomplete: true) %></li>
                          <li><%= link_to "create new market", new_market_path %></li>
                        </ul>
                    </li>
                      <li><%= link_to "about", "/about" %></li>
                    <% if !logged_in? %>
                      <li><%= link_to "login", login_path %></li>
                      <li><%= link_to "sign up", register_path, class: "sign-up-button" %></li> 
                    <% else %>
                      <li><%= link_to current_user.username, user_path(current_user) %></li>
                      <li><%= link_to "logout", '/logout' %></li> 
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mym</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

  	<%= render 'layouts/navigation' %>
  	
  	<div class="container" id="yield-body">

		<%= render "layouts/messages" %>

		<%= yield %>
		  
	</div>

  </body>
</html>